# GENDER_CHOICES VALUES
MAN = 'MAN'
WOMAN = 'WOMAN'
NONE = 'NONE'

# STATUS_DEVICE_CHOICES VALUES
ACTIVE = 'ACTIVE'
ON_MAINTENANCE = 'ON_MAINTENANCE'
INACTIVE = 'INACTIVE'

# STATUS_MAINTENANCE_CHOICES VALUES
PENDING = 'PENDING'
IN_PROGRESS = 'IN_PROGRESS'
COMPLETED = 'COMPLETED'


GENDER_CHOICES = (
    (MAN, 'Man'),
    (WOMAN, 'Woman'),
    (NONE, 'None'),
)


STATUS_DEVICE_CHOICES = (
    (ACTIVE, 'Active'),
    (ON_MAINTENANCE, 'On Maintenance'),
    (INACTIVE, 'Inactive'),
)


STATUS_MAINTENANCE_CHOICES = (
    (PENDING, 'Pending'),
    (IN_PROGRESS, 'In Progress'),
    (COMPLETED, 'Completed'),
)
