# GENDER_CHOICES VALUES
MAN = 'MAN'
WOMAN = 'WOMAN'
NONE = 'NONE'

# STATUS_DEVICE_CHOICES VALUES
ACTIVE = 'ACTIVE'
ON_MAINTENANCE = 'ON_MAINTENANCE'
INACTIVE = 'INACTIVE'


GENDER_CHOICES = (
    (MAN, 'Man'),
    (WOMAN, 'Woman'),
    (NONE, 'None'),
)


STATUS_DEVICE_CHOICES = (
    (ACTIVE, 'Active'),
    (ON_MAINTENANCE, 'On Maintenance'),
    (INACTIVE, 'Inactive'),
)
