from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    DepartmentViewSet,
    UserViewSet,
    MaintenanceInterventionViewSet,
    DeviceViewSet,
    SupplierViewSet,
    SoftwareViewSet
)

# Initialize the DefaultRouter
router = DefaultRouter()

# Register each ViewSet with the router
# The 'basename' argument ensures unique URL naming, especially useful if querysets lack a .model attribute
router.register(r'departments', DepartmentViewSet, basename='department')
router.register(r'users', UserViewSet, basename='user')
router.register(r'maintenance-interventions', MaintenanceInterventionViewSet, basename='maintenanceintervention')
router.register(r'devices', DeviceViewSet, basename='device')
router.register(r'suppliers', SupplierViewSet, basename='supplier')
router.register(r'softwares', SoftwareViewSet, basename='software')

# Define the URL patterns by including the router's URLs
urlpatterns = [
    path('', include(router.urls)),  # Includes all routes generated by the router
]
